name: Build and test matrix

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
         pip install --upgrade pip
         pip install flake8 pytest wheel
    - name: Install HDF5 on macOS
      if: matrix.os == 'macOS-latest'
      run: |
         brew install hdf5 c-blosc
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --select=E9,F63,F7 --show-source --statistics
        # exit-zero treats all errors as warnings. The Sfepy style should be 79 chars
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: install sfepy
      run: |
        pip install .
    - name: Test with pytest
      run: |
        # We create a special directory for running tests, to ensure that the
        # installed package is used, rather than the source in current
        # directory.
        mkdir -p sfepy-testing
        cd sfepy-testing
        pytest ../sfepy/tests -v -x --durations=10
